SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

-- 특정 컬럼만 조회하기
-- 문자와 날짜는 왼쪽에, 숫자는 오른쪽에 표시됨
SELECT FIRST_NAME, HIRE_DATE, EMAIL, SALARY FROM EMPLOYEES;

-- 컬럼명 자리에서는 숫자 또는 날짜가 연산이 가능
SELECT FIRST_NAME, HIRE_DATE, EMAIL, SALARY, SALARY+SALARY*0.1 FROM EMPLOYEES;

-- PK(기본키)는 EMPLOYEE_ID, FK(외래키)는 DEPARTMENT_ID
SELECT * FROM EMPLOYEES;

-- 엘리어스(별칭)
SELECT FIRST_NAME AS 별칭, SALARY AS 급여, SALARY+SALARY*0.1 "최종별칭" FROM EMPLOYEES;

-- 문자열 연결 ||
-- 홑(')안에서 '를 쓰고 싶다면 ' 2개 = ''
SELECT 'HELLO' || 'WOLRD' FROM EMPLOYEES;
SELECT FIRST_NAME || '''님의 급여는' || SALARY || '$입니다' AS 급여 FROM EMPLOYEES;

-- DISTINCT(중복 제거) 키워드 -> SELECT 다음에 붙음
SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- ROWNUM(조회된 순서), ROWID(레코드가 저장된 위치)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;

